export const styles = {
    mobileLogo:{
        cursor: 'pointer',
        maxWidth:'100%',
        height:'100%'
    },
    logo:{
        textAlign:'center',
        marginTop:'45px'
    },
    menu:{
        marginTop:'30px',
        display:'flex',
        justifyContent:'center'
    },
    btn:{
        fontSize:'16px',
        margin:'20px',
        color:'black',
        opacity:'0.6',
    },
    bar:{
        backgroundColor:'white',
        padding:'15px 10px'
    },
    banner:{
        marginTop:'25px',
    },
    btn1:{
        fontSize:'15px',
        margin:'10px',
        color:'black',
        opacity:'0.6',
        width:'200px',
        textAlign:'center',
    },
    mr:{
        margin:'15px',
        opacity:'0.6',
        fontSize:'16px',
        cursor:'pointer'
    },
    text:{
        textAlign:'center',
        opacity:'0.6',
        fontSize:'16px',
    },
    phone:{
        cursor:'pointer',
        textAlign:'center',
        opacity:'0.6',
        fontSize:'15px',
    },
    pColor:{
        color:'#9e7435'
    },
    text1:{
        width:'250px',
        margin:'15px auto',
        color:'#9e7435',
        opacity:'0.6',
        fontSize:'14px',
        cursor:'pointer',
        textAlign:'center',
    },
    container:{
        padding:'10px',
        marginBottom:'50px',
    },
    footer:{
        width:'80%',
        margin:'30px auto',
        display:'flex',
        justifyContent:'space-between',
        color:'#99997d',
        fontSize:'12px',
        fontFamily:'sans-serif'
    },
    box:{
        backgroundColor:'#282a2b',
        width:'100%',
    },
    image:{
        width:'100%',
        height:'100%'
    },
    font:{
        fontSize:'12px'
    }

}